source/api/urls.py
from django.urls import include, path

from rest_framework import routers

from api import views


router = routers.DefaultRouter()

router.register(r'comments', views.CommentViewSet)

router.register(r'like', views.LikeViewSet)

app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import IndexView, PhotoView, PhotoCreateView, PhotoUpdateView, PhotoDeleteView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', PhotoView.as_view(), name='photo_view'),
    path('product/add/', PhotoCreateView.as_view(), name='photo_add'),
    path('product/<int:pk>/change/', PhotoUpdateView.as_view(), name='photo_change'),
    path('product/<int:pk>/delete/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    ]

source/api/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Photo(models.Model):
    image = models.ImageField(upload_to='photo_images', null=False, blank=False, verbose_name='Фотография')
    signature = models.CharField(max_length=20, verbose_name='Подпись')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')
    likes = models.IntegerField(default=0, verbose_name='Лайки')
    author = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE, verbose_name='Автор')

class Comment(models.Model):
    text = models.TextField(max_length=2000, blank=False, verbose_name='Комментарий')
    image = models.ForeignKey('webapp.Photo', related_name='comments', on_delete=models.CASCADE,
                              verbose_name='Фотография')
    author = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE, verbose_name='Автор')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')

    def __str__(self):
        return self.text

class Like(models.Model):
    image = models.ForeignKey('webapp.Photo', on_delete=models.CASCADE,
                              verbose_name='Фотография', related_name='like')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', related_name='like')

source/webapp/forms.py
from django import forms

from webapp.models import Photo, Comment



class PhototForm(forms.ModelForm):

    class Meta:
        model = Photo
        fields = ['image', 'signature', 'likes', 'author']

source/api/views.py
from rest_framework import viewsets

from rest_framework.response import Response

from webapp.models import Comment, Like, Photo

from api.serializers import CommentSerializer, LikeSerializer

from rest_framework.permissions import AllowAny, DjangoModelPermissions, IsAuthenticated

SAFE_METHODS = ('GET', 'HEAD', 'OPTIONS')


class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

    def get_permissions(self):
        if self.request.method in SAFE_METHODS:
            return [AllowAny()]
        elif self.request.method == 'POST':
            return [IsAuthenticated()]
        else:
            return [DjangoModelPermissions()]

class LikeViewSet(viewsets.ModelViewSet):
    queryset = Like.objects.all()
    serializer_class = LikeSerializer


    def create(self, request, *args, **kwargs):
        pk = request.data.get('image')
        image = Photo.objects.get(pk=pk)
        if self.queryset.filter(image=image):
            return Response({'error': 'Уже есть лайк'}, status=400)
        image.likes += 1
        image.save()
        return super(LikeViewSet, self).create(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        pk = request.data.get('image')
        image = Photo.objects.get(pk=pk)
        if not self.queryset.filter(image=image):
            return Response({'error': 'Нету Лайка'}, status=400)
        image.likes -= 1
        image.save()
        return super(LikeViewSet, self).create(request, *args, **kwargs)

source/webapp/views.py
from django.http import HttpResponseRedirect
from webapp.models import Photo

from django.urls import reverse, reverse_lazy

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin

class IndexView(ListView):
    model = Photo
    template_name = 'photo/index.html'
    context_object_name = 'photos'

    ordering = ['-created_at']

    paginate_by = 3

    paginate_orphans = 1


class PhotoView(DetailView):
    model = Photo
    template_name = 'photo/view.html'


class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    template_name = 'photo/add.html'
    fields = ('image', 'signature')

    def form_valid(self, form):
        self.object = Photo.objects.create(author=self.request.user, image=form.cleaned_data['image'],
                                           signature=form.cleaned_data['signature'])

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:photo_view', kwargs={'pk': self.object.pk})

class PhotoUpdateView(PermissionRequiredMixin, UpdateView):
    model = Photo

    permission_required = 'webapp.change_photo'
    permission_denied_message = "Доступ запрещён"

    template_name = 'photo/change.html'
    fields = ('image', 'signature', 'author')
    context_object_name = 'photo'

    def has_permission(self):
        return super().has_permission() or self.photo_author(self.request.user)

    def photo_author(self, user):
        return self.get_object().author == user

    def get_success_url(self):
        return reverse('webapp:photo_view', kwargs={'pk': self.object.pk})


class PhotoDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'photo/delete.html'

    model = Photo

    permission_required = 'webapp.delete_photo'
    permission_denied_message = "Доступ запрещён"

    context_object_name = 'photo'


    success_url = reverse_lazy('webapp:index')

    def has_permission(self):
        return super().has_permission() or self.photo_author(self.request.user)

    def photo_author(self, user):
        return self.get_object().author == user

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Фото{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar">
    <div class="container">
        <ul class="menu">
            <li><a href="{% url 'webapp:index' %}">Главная страница</a></li>
            {% if request.user.is_authenticated %}
                <li class="menu-right">Привет {{ user }}<a href="{% url 'webapp:logout' %}" class="nav-link">Выход</a></li>
            {% else %}
                <li class="menu-right"><a href="{% url 'webapp:login' %}" class="nav-link">Вход</a></li>
            {% endif %}
            {% block menu %}{% endblock %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script type="application/javascript" src="{% static "js/main.js" %}"></script>
</body>

source/webapp/templates/partial/form.html
{% csrf_token %}

{% for error in form.not_field_errors %}
    <p class="form-error">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
    <p>{{ field }}</p>
    {% for error in field.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
{% endfor %}

<p><input type="submit" value="{{ button_text }}"></p>

source/webapp/templates/partial/pagination.html
<div class="pagination">

    <span class="step-links">

        <a href="?{% if query %}{{ query }}&{% endif %}page=1">&laquo; В начало</a>

        {% if page_obj.has_previous %}

            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">Назад</a>

        {% else %}

            <span class="page-disabled">Назад</span>

        {% endif %}



        <span class="current">

            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.

        </span>



        {% if page_obj.has_next %}

            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Далее</a>

        {% else %}

            <span class="page-disabled">Далее</span>

        {% endif %}

        <a href="?{% if query %}{{ query }}&{% endif %}page={{ paginator.num_pages }}">В конец &raquo;</a>

    </span>

    <div>
        {% for page in paginator.page_range %}
            {% if page_obj.number == page %}
                <span class="page-active">{{ page }}</span>
            {% else %}
                <a href="?{% if query %}{{ query }}&{% endif %}page={{ page }}">{{ page }}</a>
            {% endif %}
        {% endfor %}
    </div>

</div>

source/webapp/templates/photo/add.html
{% extends 'base.html' %}
{% block title %}Добавить Фото{% endblock %}
{% block content %}
    <h1 class="text-center">Добавить фото</h1>
        <form action="{% url "webapp:photo_add" %}" method="POST" enctype="multipart/form-data">
            {% include 'partial/form.html' with button_text='Создать' %}
        </form>
{% endblock %}

source/webapp/templates/photo/change.html
{% extends 'base.html' %}
{% block title %}Обновить Фото{% endblock %}
{% block content %}
    <h1 class="text-center">Обновить Фото</h1>
        <form action="{% url "webapp:photo_change" photo.pk %}" method="POST" enctype="multipart/form-data">
            {% include 'partial/form.html' with button_text='Обновить' %}
        </form>
{% endblock %}

source/webapp/templates/photo/delete.html
{% extends 'base.html' %}

{% block title %}Удалить Фото{% endblock %}

{% block menu %}
    <li><a href="{% url 'webapp:photo_view' photo.pk %}">Подробнее</a></li>
{% endblock %}

{% block content %}
            <h1>Вы уверены что хотите удалить "{{ photo.image }}"?</h1>
            <form method="POST" action="{% url 'webapp:photo_delete' photo.pk %}" class="text-center">
                {% csrf_token %}
                <p><input type="submit" value="Да"></p>
                <p><a href="{% url 'webapp:photo_view' photo.pk %}">Нет</a></p>
            </form>
{% endblock %}

source/webapp/templates/photo/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block menu %}
    {% if request.user.is_authenticated %}
    <li><a href ="{% url 'webapp:photo_add' %}">Добавить Фото</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Фото:</h1>
    <hr/>
    {% if is_paginated %}

       {% include 'partial/pagination.html' %}

   {% endif %}
    {% for photo in photos %}
        {% if photo.image %}
            <img src="{{ photo.image.url }}" width="200" height="200"  alt="{{ photo.signature }}">
        {% else %}
            <img src="{% static "images/nophoto.png" %}" width="200" height="200" alt="Заглушка" >
        {% endif %}
            <p>Подпись: {{ photo.signature }}</p>
            <p>Автор: {{ photo.author }}</p>
            <p>Cоздана: {{ photo.created_at|date:'Y-m-d H:i:s' }}</p>
            <p>Лайки: {{ photo.likes }}</p>
            <a href="{% url 'webapp:photo_view' photo.pk %}">Подробнее.</a>
            {% if perms.webapp.change_photo or request.user == photo.author%}
                <a href="{% url 'webapp:photo_change' photo.pk %}">Обновить</a>
            {% endif %}
            {% if perms.webapp.delete_photo or request.user == photo.author%}
                <a href="{% url "webapp:photo_delete" photo.pk %}">Удалить</a>
            {% endif %}
        <hr/>
    {% endfor %}
    {% if is_paginated %}

       {% include 'partial/pagination.html' %}

   {% endif %}
{% endblock %}

source/webapp/templates/photo/view.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ photo.signature }}{% endblock %}

{% block menu %}
    {% if perms.webapp.change_photo or request.user == photo.author%}
        <li><a href="{% url 'webapp:photo_change' photo.pk %}">Обновить</a></li>
    {% endif %}
    {% if perms.webapp.delete_photo or request.user == photo.author%}
        <li><a href="{% url 'webapp:photo_delete' photo.pk %}">Удалить</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    {% if photo.image %}
        <img class="photo-image" src="{{ photo.image.url }}" width="250" height="250" alt="{{ photo.signature }}">
    {% else %}
        <img src="{% static "images/nophoto.png" %}" width="200" height="200" alt="Заглушка" >
    {% endif %}
    <div class="pre-1">
        <p>Подпись: {{ photo.signature }}</p>
        <p>Автор: {{ photo.author }}</p>
        <p>Cоздана: {{ photo.created_at|date:'Y-m-d H:i:s' }}</p>
        <p>Лайки: {{ photo.likes}}</p>
        {% if request.user.is_authenticated %}
            <button type="button" class="btn btn-success">Like</button>
            <button type="button" class="btn btn-danger">Dislike</button>
        {% endif %}
    </div>
    <hr/>
    <h3>Отзывы:</h3>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    <div class="comment-list">
        {% for comment in photo.comments.all %}
            <div class="comment">
                <p><strong>Автор:</strong> {{ photo.author }}</p>
                <p><strong>Дата создания:</strong> {{ comment.created_at|date:'Y-m-d H:i:s' }}</p>
                <div class="pre">{{ comment.text }}</div>
            <hr>
            </div>
        {% empty %}
            <p>Нет отзывов</p>
        {% endfor %}
    </div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}